services:

  env-base:
    image: ${REGISTRY}/inginious/env-base:${VERSION}
    build:
      context: base-containers/base/
    command: /bin/true

  env-default:
    image: ${REGISTRY}/inginious/env-default:${VERSION}
    build:
      context: base-containers/default/
    depends_on:
      - env-base
    command: /bin/true

  env-python3:
    image: ${REGISTRY}/inginious/env-python3:${VERSION}
    command: /bin/true

  base:
    image: ${REGISTRY}/inginious/core-base:${VERSION}
    build:
      dockerfile: deploy/inginious-base.containerfile
      args:
        VERSION: ${VERSION}
        REGISTRY: ${REGISTRY}
        SCM_VERSION: ${SCM_VERSION}
    command: /bin/true

  db:
    image: mongo:6.0.2
    networks:
      - inginious

  backend:
    image: ${REGISTRY}/inginious/core-backend:${VERSION}
    depends_on:
      - base
    build:
      dockerfile: deploy/backend.containerfile
      args:
        VERSION: ${VERSION}
        REGISTRY: ${REGISTRY}
        SCM_VERSION: ${SCM_VERSION}
    environment:
      AGENT: "tcp://0.0.0.0:2001"
      CLIENT: "tcp://0.0.0.0:2000"
    networks:
      - inginious

  agent-docker:
    image: ${REGISTRY}/inginious/core-agent_docker:${VERSION}
    depends_on:
      - backend
    deploy:
      replicas: 1
    build:
      dockerfile: deploy/agent-docker.containerfile
      args:
        VERSION: ${VERSION}
        REGISTRY: ${REGISTRY}
        SCM_VERSION: ${SCM_VERSION}
    environment:
      BACKEND: "tcp://backend:2001"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     # See https://github.com/INGInious/INGInious/issues/352
     - ${TASKS_DIR}:/inginious/tasks
     - ${BACKUPS_DIR}:/inginious/backups
     # See https://github.com/INGInious/INGInious/issues/799
     - /tmp/agent_data/:/tmp/agent_data/
    networks:
     - inginious

  agent-mcq:
    image: ${REGISTRY}/inginious/core-agent_mcq:${VERSION}
    depends_on:
      - backend
    deploy:
      replicas: 1
    build:
      dockerfile: deploy/agent-mcq.containerfile
      args:
        VERSION: ${VERSION}
        REGISTRY: ${REGISTRY}
        SCM_VERSION: ${SCM_VERSION}
    environment:
      BACKEND: "tcp://backend:2001"
    volumes:
     # See https://github.com/INGInious/INGInious/issues/352
     - ${TASKS_DIR}:/inginious/tasks
     - ${BACKUPS_DIR}:/inginious/backups
     # See https://github.com/INGInious/INGInious/issues/799
     - /tmp/agent_data/:/tmp/agent_data/
    networks:
     - inginious

  frontend:
    image: ${REGISTRY}/inginious/core-frontend:${VERSION}
    build:
      dockerfile: deploy/frontend.containerfile
      args:
        VERSION: ${VERSION}
        REGISTRY: ${REGISTRY}
        SCM_VERSION: ${SCM_VERSION}
    depends_on:
      - backend
      - agent-docker
      - agent-mcq
      - env-base
      - env-default
    environment:
      - INGINIOUS_WEBAPP_HOST=0.0.0.0
    volumes:
      - ${CONFIG_FILE}:/inginious/configuration.yaml
      - ${TASKS_DIR}:/inginious/tasks
      - ${BACKUPS_DIR}:/inginious/backups
      - ${PLUGINS_DIR}:/inginious/plugins
    ports:
      - ${LISTEN_PORT}:8080
    networks:
      - inginious

networks:
  inginious:
